### ISSUE TITLE
If this is the source repository for kigawas.me ...

### ISSUE THREAD

**Issue by adlai** [kigawas/kigawas.github.io#3]
... then please reduce the amount of javascript in the pages that can plausibly be static.

**Comment by adlai** [comment]
Specifically, [this line](https://github.com/kigawas/kigawas.github.io/blob/606b3078b0ce9766d47d3f6388b6f45f6ca7eb9b/about/index.html#L12) is responsibly for a cute bunch of emoticon buttons on your site, that do not allow unclicking; thus, I have left the sad one selected.

**Comment by kigawas** [comment]
Files in this repo are generated by hugo

Original blog repo is
https://github.com/kigawas/blog

**Comment by kigawas** [comment]
Just disabled the disqus reaction

**Comment by adlai** [comment]
Thank you!
